name: nest_care
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  google_fonts: ^3.0.1
  flutter_svg: ^1.1.5
  flutter:       # Required for every Flutter project
    sdk: flutter # Required for every Flutter project
  simple_animations: ^1.3.3
  cupertino_icons: ^1.0.2 # Only required if you use Cupertino (iOS style) icons
  cloud_firestore: ^3.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter # Required for a Flutter project that includes tests
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true # Required if you use the Material icon font

  assets:  # Lists assets, such as image files
    - assets/logo.png
